/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 1;
  /** RegularExpression Id. */
  int RPAREN = 2;
  /** RegularExpression Id. */
  int LCOUCH = 3;
  /** RegularExpression Id. */
  int RCOUCH = 4;
  /** RegularExpression Id. */
  int VIRG = 5;
  /** RegularExpression Id. */
  int DOT = 6;
  /** RegularExpression Id. */
  int EQ = 7;
  /** RegularExpression Id. */
  int LBRACE = 8;
  /** RegularExpression Id. */
  int RBRACE = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;
  /** RegularExpression Id. */
  int LESS = 11;
  /** RegularExpression Id. */
  int NOT = 12;
  /** RegularExpression Id. */
  int PLUS = 13;
  /** RegularExpression Id. */
  int MINUS = 14;
  /** RegularExpression Id. */
  int STAR = 15;
  /** RegularExpression Id. */
  int AND = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int NEW = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int LENGTH = 23;
  /** RegularExpression Id. */
  int THIS = 24;
  /** RegularExpression Id. */
  int VOID = 25;
  /** RegularExpression Id. */
  int PRINT = 26;
  /** RegularExpression Id. */
  int BOOLEAN = 27;
  /** RegularExpression Id. */
  int INTEGER = 28;
  /** RegularExpression Id. */
  int STRING = 29;
  /** RegularExpression Id. */
  int STATIC = 30;
  /** RegularExpression Id. */
  int EXTENDS = 31;
  /** RegularExpression Id. */
  int RETURN = 32;
  /** RegularExpression Id. */
  int CLASS = 33;
  /** RegularExpression Id. */
  int PUBLIC = 34;
  /** RegularExpression Id. */
  int MAIN = 35;
  /** RegularExpression Id. */
  int IDENTIFIER = 36;
  /** RegularExpression Id. */
  int DIGIT = 37;
  /** RegularExpression Id. */
  int LETTER = 38;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"<\"",
    "\"!\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"&&\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"new\"",
    "\"true\"",
    "\"false\"",
    "\"length\"",
    "\"this\"",
    "\"void\"",
    "\"System.out.println\"",
    "\"boolean\"",
    "\"int\"",
    "\"String\"",
    "\"static\"",
    "\"extends\"",
    "\"return\"",
    "\"class\"",
    "\"public\"",
    "\"main\"",
    "<IDENTIFIER>",
    "<DIGIT>",
    "<LETTER>",
    "<INTEGER_LITERAL>",
    "<token of kind 40>",
    "<token of kind 41>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
  };

}
